file_upload/urls.py
from django.urls import path
from . import views

app_name = "file_upload"
urlpatterns = [
    path("", views.FileListView.as_view(), name="file_list"),
    path("form_upload/", views.FileFormView.as_view(), name="form_upload"),
    path("model_form_upload/", views.FileCreateView.as_view(), name="model_form_upload"),
    path("delete_file/<int:pk>/", views.FileDeleteView.as_view(), name="delete_file"),
    path("download/<file_path>/", views.file_download, name="file_download"),
]

smallProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include("user.urls")),
    path('', views.home, name='home'),
    path('captcha', include('captcha.urls')),
    path('file_upload/', include('file_upload.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file_upload/models.py
from django.db import models
import uuid
from user.models import UserProfile
import os


def user_directory_path(instance, filename):
    file_type = filename.split(".")[-1]
    filename = "{0}.{1}".format(uuid.uuid4().hex[:10], file_type)
    return os.path.join("files", file_type, filename)


class File(models.Model):
    title = models.CharField(max_length=50)
    file = models.FileField(upload_to=user_directory_path)
    created_time = models.DateTimeField(auto_now_add=True)

user/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    gender = (
        ('male', '男'),
        ('female', '女'),
    )
    nick_name = models.CharField(max_length=10, unique=True, blank=True)
    tel = models.BigIntegerField(unique=True)
    sex = models.CharField(max_length=10, choices=gender)
    created_time = models.DateTimeField(auto_now_add=True)
    last_time = models.DateTimeField(auto_now=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nick_name

file_upload/views.py
import uuid
import os
from django.shortcuts import render, redirect
from django.http import Http404, FileResponse
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, FormView, CreateView
from django.utils.http import urlquote
from .form import FileUploadForm, FileUploadModelForm
from .models import File


# 展示上传文件（通用视图）
class FileListView(ListView):
    model = File
    context_object_name = "files"
    template_name = "file_upload/file_list.html"


# 展示上传文件（方法）
'''
def file_list(request):
    files = File.objects.all()
    context = dict()
    context['files'] = files
    return render(request, "file_upload/file_list.html", context)
'''


# 上传文件处理方法
def handle_uploaded_file(file):
    file_type = file.name.split(".")[-1]
    file_name = "{}.{}".format(uuid.uuid4().hex[:10], file_type)
    file_path = os.path.join("files", file_type, file_name)
    absolute_file_path = os.path.join('media', 'files', file_type, file_name)

    directory = os.path.dirname(absolute_file_path)
    if not os.path.exists(directory):
        os.makedirs(directory)

    with open(absolute_file_path, "wb+") as destination:
        for chunck in file.chunks():
            destination.write(chunck)
    return file_path


# 普通表单上传文件（通用视图）
class FileFormView(FormView):
    form_class = FileUploadForm
    success_url = reverse_lazy("file_upload:file_list")
    template_name = "file_upload/form_upload.html"

    def form_valid(self, form):
        file = File()
        file.title = form.cleaned_data['title']
        file_upload = form.cleaned_data['file']
        file.file = handle_uploaded_file(file_upload)
        file.save()
        return super().form_valid(form)


# 普通表单上传文件（方法）
'''
def form_upload(request):
    if request.method == "POST":
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            file_upload = form.cleaned_data['file']
            file = File()
            file.file = handle_uploaded_file(file_upload)
            file.title = title
            file.save()
            return redirect("file_upload:file_list")
    else:
        form = FileUploadForm()
    context = dict()
    context['form'] = form
    context['title'] = "普通表单上传文件"
    return render(request, "file_upload/form_upload.html", context)
'''


# 使用ModelForm上传文件（通用视图）
class FileCreateView(CreateView):
    model = File
    fields = ['title', 'file']
    success_url = reverse_lazy("file_upload:file_list")
    template_name = "file_upload/form_upload.html"


# 使用ModelForm上传文件方法
'''
def form_upload_by_model_form(request):
    if request.method == "POST":
        form = FileUploadModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("file_upload:file_list")
    else:
        form = FileUploadModelForm()
    context = dict()
    context['title'] = "普通表单上传文件"
    context['form'] = form
    return render(request, "file_upload/form_upload.html", context)
'''


# 文件删除（通用视图）
class FileDeleteView(DeleteView):
    model = File
    context_object_name = "file"
    success_url = reverse_lazy("file_upload:file_list")
    template_name = "file_upload/delete_file.html"

    def get_success_url(self):
        file = File.objects.get(pk=self.kwargs['pk'])
        file_dir = os.path.join("media", str(file.file))
        os.remove(file_dir)
        return super().get_success_url()


# 文件下载
def file_download(request, file_path):
    file = File.objects.get(file=file_path)
    file_path = os.path.join("media", file_path)
    file_type = file_path.split('.')[-1]
    try:
        response = FileResponse(open(file_path, 'rb'))
        response['content_type'] = "application/octet-stream"
        response['Content-Disposition'] = "attachment; filename={0}.{1}".format(urlquote(file.title), file_type)
        return response
    except Exception:
        raise Http404

smallProject/views.py
from django.shortcuts import render


def home(request):
    return render(request, "home.html")

user/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .form import RegisterForm, LoginForm
from .models import UserProfile
from django.contrib import auth
from django.contrib.auth.models import User


def register(request):
    if request.user.is_authenticated:
        return redirect(reverse("home"))
    else:
        if request.method == "POST":
            form = RegisterForm(request.POST)
            if form.is_valid():
                sex = form.cleaned_data['sex']
                nick_name = form.cleaned_data['nick_name']
                tel = form.cleaned_data['tel']
                print(type(tel))
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                email = form.cleaned_data['email']
                user = User.objects.create_user(username=username, password=password, email=email)
                user_profile = UserProfile.objects.create(nick_name=nick_name, tel=tel, sex=sex, user=user)
                auth.login(request, user)
                return redirect(reverse('home'))
        else:
            form = RegisterForm()
        context = {"form": form}
        return render(request, "user/register.html", context)


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data['user']
            auth.login(request, user)
            return redirect(reverse("home"))
    else:
        form = LoginForm()

    context = {'form': form}
    return render(request, 'user/login.html', context)


def logout(request):
    auth.logout(request)
    return redirect(reverse('home'))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/bootstrap.min.css" %}">
    <script type="text/javascript" src="{% static "bootstrap-3.3.7/jquery-1.12.4.min.js" %}"></script>
    <script type="text/javascript" src="{% static "bootstrap-3.3.7/js/bootstrap.min.js" %}"></script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}">我的网站</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'home' %}">主页</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">
                                {{ request.user.userprofile.nick_name }} <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">个人信息</a></li>
                                <li><a href="{% url 'user:logout' %}">退出</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'user:register' %}">注册</a></li>
                        <li><a href="{% url 'user:login' %}">登录</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/file_upload/delete_file.html
{% extends "base.html" %}

{% block title %}
    确认删除
{% endblock %}

{% block content %}
    <p>你确认要删除{{ file.title }}吗？</p>
    <form action="" method="post">
        {% csrf_token %}
        <button type="button"><a href="{% url "file_upload:file_list" %}">取消</a></button>
        <button type="submit">确认</button>
    </form>
{% endblock %}

templates/file_upload/file_list.html
{% extends "base.html" %}

{% block title %}
    文件列表
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <table class="table table-bordered">
                <tr>
                    <th>文件名</th>
                    <th>文件链接</th>
                    <th>文件地址</th>
                    <th>文件大小</th>
                    <th>功能</th>
                </tr>
                {% for file in files %}
                    <tr>
                        <td>{{ file.title }}</td>
                        <td>{{ file.file.url }}</td>
                        <td>{{ file.file.name }}</td>
                        <td>{{ file.file.size | filesizeformat }}</td>
                        <td>
                            <a href="{% url "file_upload:delete_file" file.pk %}" >删除</a>&nbsp;&nbsp;
                            <a href="{% url "file_upload:file_download" file.file.name %}">下载</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                {% endfor %}
            </table>
            <p><a href="{% url "file_upload:form_upload" %}">普通表单上传</a></p>
            <p><a href="{% url "file_upload:form_upload" %}">ModelForm表单上传</a></p>
        </div>
    </div>

{% endblock %}

templates/file_upload/form_upload.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <input type="submit" value="上传">
            </form>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}
    主页
{% endblock %}

{% block content %}
    <ul>
        <li><a href="{% url "file_upload:file_list" %}">文件上传及下载</a></li>
    </ul>
{% endblock %}

templates/user/login.html
{% extends "base.html" %}

{% block title %}
    登录
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>登录</h3>
                </div>
                <div class="panel-body">
                    <form action="" class="form-horizontal" method="post">
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">
                                    {{ field.label }}
                                </label>
                                <div class="col-sm-10">
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                </div>
                            </div>
                        {% endfor %}
                        {{ form.non_field_errors }}
                        <button type="submit" class="btn btn-default pull-right">登录</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/user/register.html
{% extends "base.html" %}

{% block title %}
    注册
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>注册</h3>
                </div>
                <div class="panel-body">
                    <form action="" class="form-horizontal" method="post">
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">
                                    {{ field.label }}
                                </label>
                                <div class="col-sm-10">
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                </div>
                            </div>
                        {% endfor %}
                        {{ form.non_field_errors }}
                        <button type="submit" class="btn btn-default pull-right">注册</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}